# Site settings
title: Learning it hard way!
email: hacker.asif@gmail.com
description: "dhoondta phirta hoon apne aapko<br/>aap hi goya musafir, aap hi manzil hun main"
baseurl: ""
url: "http://bawlipoonch.github.io"
twitter_username: mdasif
github_username:  mdasif
facebook_username:  hacker.asif

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["node_modules"]

plugins:
 - jekyll-feed
 - jemoji
 - jekyll-mentions
 - jekyll-include-cache
 - jekyll-paginate

jekyll-mentions:
  base_url: https://twitter.com