# Site settings
title: Learning it hard way!
email: hacker.asif@gmail.com
description: "haan yehi rasta hai tera tune ab jana hai"
baseurl: ""
url: "http://bawlipoonch.github.io"
twitter_username: mdasif
github_username:  mdasif
facebook_username:  hacker.asif

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
